INSERT INTO PRODUCT_MASTER(PRODUCT_ID, PRODUCT_TYPE) VALUES(1, 'Home Loan');           
INSERT INTO PRODUCT_MASTER(PRODUCT_ID, PRODUCT_TYPE) VALUES(2, 'Personal Loan');    
INSERT INTO FIELD_MASTER (field_id,product_id,field_name,minval,maxval) values (1,1,'age','21','65');
INSERT INTO FIELD_MASTER(FIELD_ID, MAXVAL, MINVAL, FIELD_NAME, PRODUCT_ID) VALUES(2, '100000', '3000', 'withdraw', 2); 
INSERT INTO FIELD_MASTER(FIELD_ID, MAXVAL, MINVAL, FIELD_NAME, PRODUCT_ID) VALUES(3, '8.5', '12.8', 'rate', 1);   
